# Working Notes 1: Modelling Tarot Reversals

In basic terms, I'm currently grappling with how to model card reversals in this weird little shonky tarot-reading prototype Python programme I've been working on. With genai support, I've identified three possible approaches. With the Tarot de Marseille as my main go-to, for now, I _think_ I only want reversals to apply to cards in the Major Arcana, based on it being difficult to discern the orientation of the "pips" of the Minor Arcana.

I'm leaning towards a `Card` object class, as something that supports some of my other plans, and will (I think?) enable tracking and analysis (e.g. percentage of reversed cards in a given spread, different cards' orientations over time). That said, I'm keen to avoid accidentally painting myself into a corner, and want to make sure I haven't overlooked any obvious issues or drawbacks.

What I'd find useful would be for both of us to annotate / add footnotes to this markdown file, as a way of riffing and elaborating on – or extending – the summaries I've managed to elicit from the machines.

|                           | Boolean Flags                                                                                                                                                                                     | `Card` Object Class                                                                                                              | Tuples                                                                                                                                                                                                         |
| ------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| **Ontology / ontography** | Treats reversals as a binary property of cards. A flat, global property, reversal is either present or absent, with no nuance. Doesn't capture the unique nature of each card's reversal meaning. | Models each card as a unique object, with reversal as one of potentially many properties. Allows for a richer symbolic ontology. | Represents each card as an immutable pairing of card identity and reversal state. Each card's tuple is a self-contained representation.  Ontologically minimal, with relationships between cards not captured. |
| **Representation**        | Reversal is a simple True/False value, easy to store and check. But lacks semantic meaning.                                                                                                       | Reversal can be represented in various ways on the object (boolean, enum, string). More flexibility and expressiveness.          | Tuple pairs the card name with a reversal indicator (e.g. `(card, True)`). Minimal and unambiguous.                                                                                                            |
| **Mutability**            | Reversal state can be easily changed by flipping the Boolean flag. Card meaning is mutable.                                                                                                       | Reversal is an attribute of the Card object. Mutability depends on implementation (e.g. getter/setter methods).                  | Tuples are immutable by definition. Reversal state cannot be changed once set, enforcing card meaning.                                                                                                         |
| **Usage**                 | Requires constantly checking the flag when interpreting a card's meaning. Can lead to convoluted conditional logic.                                                                               | Card behaviors can be encapsulated on the object with methods like `is_reversed()` or `meaning()`. More object-oriented usage.   | Unpacking the tuple and checking the reversal indicator becomes repetitive. Less readable than objects.                                                                                                        |
| **Extensibility**         | Limited to two reversal states. Hard to extend if you later want multiple reversal meanings per card.                                                                                             | New reversal states can be added by extending the `Card` class. Supports different reversal types per card.                      | Tuples can be extended to triplets, etc. But too many items can become unwieldy to unpack and reference.                                                                                                       |
| **Temporality**           | Reversal state exists in an eternal present, with no history or evolution over time.                                                                                                              | Card objects can accumulate a history of their reversal states over time, capturing an evolving understanding.[^1]                   | Each tuple represents a fixed reversal state, with no inherent sense of change or evolution over time.                                                                                                         |
| **Embodiment**            | Reversal is a disembodied, abstract property, not tied to the card's visual symbolism or imagery.                                                                                                 | Reversal can be tied to the card's visual elements through object properties, embodying symbolic meanings.                       | Tuples are abstract data structures, not inherently tied to the embodied imagery and symbolism of the cards.                                                                                                   |

[^1]: (J) The idea of an accumulating history is very exciting to me.